name: sous-project
recipe: drupal9
config:
  webroot: web
  php: "8.1"
services:
  appserver:
    build:
      - composer install
      - cp web/sites/default/default.settings.php web/sites/default/settings.php
  node:
    type: node:16
    build:
      - npm install
      - npm install @emulsify/cli
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://sous-project.lndo.site"
  npm:
    service: node
  emulsify:
    service: node
  compound-install:
    service: node
    description: "Install Compound component library"
    cmd: cd $LANDO_MOUNT && cd web/themes/custom/sous-project && emulsify system install compound
