name: sous-project
recipe: drupal9
config:
  webroot: web
  php: "8.1"
  composer_version: '2.5.5'
  # M1/2 Mac settings
  xdebug: false
  index: false
  edge: false
  cache: false
services:
  appserver:
    build:
      - composer install
      - cp web/sites/default/default.settings.php web/sites/default/settings.php
    build_as_root:
      - apt update -y && apt install -y apt-transport-https build-essential unzip
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
      - chown -R www-data /usr/lib/node_modules
      - chown -R www-data /usr/bin
      - npm install -g npm
      - npm install -g @emulsify/cli
  chromedriver:
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      expose:
        - "4444"
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://sous-project.lndo.site"
  node:
    service: appserver
  npm:
    service: appserver
  emulsify:
    service: appserver
  # compound-install:
  #   service: node
  #   description: "Install Compound component library"
  #   cmd: cd $LANDO_MOUNT && cd web/themes/custom/sous-theme && emulsify system install compound
  sous-builder-install:
    service: appserver
    description: "Install Sous Builder module and theme demo"
    cmd: composer config repositories.2 git https://github.com/fourkitchens/sous-builder.git && composer config repositories.3 git https://github.com/fourkitchens/sousdemo.git && composer require fourkitchens/sous-builder && composer require fourkitchens/sousdemo && drush pm:enable sous_builder -y && drush theme:enable sousdemo -y && drush config-set system.theme default sousdemo -y
